python ../../train/train_trans_dec.py \
--dataset shapestacks \
--evaluate ari \
--monitor avg_ARI_FG \
--gpus 1 \
--batch_size 128 \
--num_slots 12 \
--log_name trans_dec \
--check_val_every_n_epoch 1 \
--is_logger_enabled \
--seed 42 \
--init_method 'embedding' \
--truncate 'bi-level' \